# Generated by Django 4.2.6 on 2023-10-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='path'),
        ),
    ]
