# Generated by Django 4.2.6 on 2023-10-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='words',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='wordcount.words'),
        ),
    ]
